name: jolt
description: A complete alternative to Material Design for Flutter.
version: 0.0.1
homepage: flutterjolt.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  bitsdojo_window: ^0.1.5
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_localizations: 
    sdk: flutter
  flutter_portal: ^1.1.3
  hive_flutter: ^2.0.0-dev
  persistent_header_adaptive: ^2.0.0
  # FIX FOR https://github.com/phosphor-icons/flutter/issues/16
  # phosphor_flutter: ^2.0.0
  phosphor_flutter:
    git:
      url: https://github.com/phosphor-icons/flutter.git
  sliver_tools: ^0.2.10
  tinycolor2: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: false
