name: jolt
description: A complete alternative to Material Design for Flutter.
version: 0.0.1
homepage: flutterjolt.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_hooks: ^0.20.4
  freezed_annotation: ^2.4.1
  nested: ^1.0.0
  shared_preferences: ^2.2.2
  tinycolor2: ^3.0.1
  # phosphor_flutter: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: false
