name: jolt
description: A complete alternative to Material Design for Flutter.
version: 0.0.1
homepage: flutterjolt.dev

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  hive_flutter: ^2.0.0-dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: false
