name: jolt
description: A complete alternative to Material Design for Flutter.
version: 0.0.1
homepage: flutterjolt.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  boxy: ^2.2.0
  flutter:
    sdk: flutter
  sliver_tools: ^0.2.12
  # flutter_animate: ^4.1.1+1
  # flutter_hooks: ^0.20.4
  # freezed_annotation: ^2.4.1
  tinycolor2: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  # freezed: ^2.4.6
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: false
