// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 2.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'example';

  static const String iconsLogoDarkPng = 'assets/icons/logo_dark.png';

  static const String iconsLogoLightPng = 'assets/icons/logo_light.png';
}
