name: jolt
repository: https://github.com/asteroid-studios/jolt

packages:
  - "apps/**"
  - "packages/**"

ignore:
  - "packages/jolt_cli/bricks/ui/__brick__"

ide:
  intellij:
    enabled: false

scripts:
  analyze:
    exec: dart analyze .
