name: jolt
repository: https://github.com/asteroid-studios/jolt

packages:
  - "apps/*"
  - "packages/**"

command:
  bootstrap:
    usePubspecOverrides: true

ide:
  intellij:
    enabled: false
  
scripts:
  analyze:
    exec: dart analyze .