include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    avoid_print: true
    lines_longer_than_80_chars: false
    prefer_constructors_over_static_methods: false
    avoid_positional_boolean_parameters: false

analyzer:
  enable-experiment:
    - macros
