name: ui
description: "A UI library for Flutter."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.18.0
  extended_sliver: ^2.1.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  gap: ^3.0.1
  jolt:
  phosphor_flutter: ^2.0.1
  shared_preferences: ^2.2.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: false
  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/satoshi/Satoshi-Variable.ttf
        - asset: fonts/satoshi/Satoshi-VariableItalic.ttf
          style: italic
    - family: Sono
      fonts:
        - asset: fonts/sono/Sono-VariableFont.ttf
