name: ui
description: "A UI library for Flutter."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0"
  flutter: ">=3.0.0"

dependencies:
  boxy: ^2.2.0
  change_case: ^2.1.0
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  gap: ^3.0.1
  jolt:
  macros: ^0.1.2-main.4
  native_storage: ^0.2.2
  phosphor_flutter: ^2.0.1
  sliver_tools: ^0.2.12
  visibility_detector: ^0.4.0+2

dev_dependencies:
  alchemist: ^0.10.0
  flutter_test:
    sdk: flutter
  meta: ^1.15.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: false
  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/satoshi/Satoshi-Variable.ttf
        - asset: fonts/satoshi/Satoshi-VariableItalic.ttf
          style: italic
    - family: Sono
      fonts:
        - asset: fonts/sono/Sono-VariableFont.ttf
