name: ui
description: "A UI library for Flutter."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  jolt:

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: false
  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/satoshi/Satoshi-Variable.ttf
        - asset: fonts/satoshi/Satoshi-VariableItalic.ttf
          style: italic
