name: example
description: An example app utilizing the jolt package
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  assets_gen: ^1.5.0
  bitsdojo_window: ^0.1.5
  collection: ^1.17.1
  faker: ^2.1.0
  flutter:
    sdk: flutter
  # flutter_highlighting: ^0.9.0+11.8.0
  flutter_highlighting:
    git:
      url: https://github.com/asteroid-studios/dart-highlighting.git
      path: flutter_highlighting
  flutter_jimtl: ^0.0.3
  flutter_native_splash: ^2.3.1
  flutter_web_plugins:
    sdk: flutter
  intl:
  path_provider:
  ui:
    path: packages/ui
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  jimtl_codegen: ^0.0.4
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: false
  assets:
    - assets/arb/
    - assets/icons/

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#f8fafc"
  color_dark: "#020617"

# flutter pub run assets_gen build
assets_gen:
  code_style: lowerCamelCase
  output: utils/assets/assets.dart
  omit_path_levels: 1
  gen_package_path: false
  exclude:
    - "**/*.arb"
