name: example
description: An example app utilizing the jolt package
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  flutter:
    sdk: flutter
  flutter_syntax_view: ^4.0.0
  flutter_web_plugins:
    sdk: flutter
  go_router: ^6.5.7
  google_fonts: ^4.0.3
  jolt: 
    path: ../../packages/jolt


dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.2.2
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: false
  assets:
    - code_snippets/
