name: jolt_copy
description: A complete alternative to Material Design for Flutter.
version: 0.0.1
homepage: flutterjolt.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  bitsdojo_window: ^0.1.5
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.3
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.4.1
  hive_flutter: ^2.0.0-dev # TODO migrate away
  nested: ^1.0.0
  shared_preferences: ^2.2.2
  persistent_header_adaptive: ^2.1.0 # TODO migrate away
  phosphor_flutter: ^2.0.1
  pull_to_refresh: ^2.0.0
  sliver_tools: ^0.2.10
  tinycolor2: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: false
