name: flutter_jolt
description: A new Flutter package project.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Extensions + Utilities
  collection: ^1.16.0
  # Dates + Internationalisation
  dart_date: ^1.1.1
  intl: ^0.17.0
  # Web
  url_strategy: ^0.2.0
  # Device and App Information
  adaptive_breakpoints: ^0.1.4
  device_info_plus: ^3.2.3
  package_info_plus: ^1.3.1
  universal_platform: ^1.0.0+1
  # App Styling
  tinycolor2: ^2.1.0
  # Connectivity
  universal_internet_checker: ^0.1.2
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Widgets
  auto_size_text: ^3.0.0
  focusable_control_builder: ^1.0.0-prerelease+1
  # Model Generation
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
    assets:
        - assets/jolt/
