name: flutter_jolt
description: A new Flutter package project.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Extensions + Utilities
  collection: ^1.16.0
  # Dates + Internationalisation
  dart_date: ^1.1.1
  # Device and App Information
  adaptive_breakpoints: ^0.1.4
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  # App Styling
  tinycolor2: ^2.1.0
  # Connectivity
  universal_internet_checker: ^0.1.2
  # Local Storage
  hive_flutter: ^1.1.0
  # Widgets
  auto_size_text: ^3.0.0
  flutter_hooks: ^0.18.5+1
  # focusable_control_builder: ^1.0.0-prerelease+1
  # TODO  ^ Doesn't inkwell do this?
  # Model Generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  theme_extensions_builder_annotation: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  theme_extensions_builder: ^2.0.1+3

flutter:
    assets:
        - assets/jolt/
