include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule

