name: example_backup
description: An example project to showcase Jolt packages
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Jolt Packages
  flutter_jolt:
    path: ../flutter_jolt
  # State Management
  hooks_riverpod: ^1.0.4
  # Supabase BackEnd
  supabase_flutter: ^0.3.2
  # Feature Flagging / Remote Config
  flagsmith: ^3.0.2
  # Error Reporting
  sentry_flutter: ^6.9.0
  # Analytics
  mixpanel_analytics: ^2.1.1
  # Deep linking
  uni_links_desktop: ^0.1.2
  # Routing
  go_router: ^4.2.2
  # Fonts
  google_fonts: ^3.0.1
  # Utilities
  universal_platform: ^1.0.0+1
  # Customising Window
  bitsdojo_window: ^0.1.2
  # TODO Remove
  adaptive_components: ^0.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.0.1
  flutter_lints: ^2.0.1

dependency_overrides:
  # TODO https://github.com/leanflutter/uni_links_desktop/issues/2
  protocol_handler: 0.1.1

flutter:
  uses-material-design: true
  assets:
    - config/local/
    - config/development/
    - config/production/

