name: jolt_cli
description: CLI for Jolt UI library
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  args: ^2.4.2
  cli_completion: ^0.5.0
  collection: ^1.17.1
  equatable: ^2.0.5
  glob: ^2.0.2
  lcov_parser: ^0.1.2
  mason: ^0.1.0-dev.52
  mason_logger: ^0.2.12
  meta: ^1.3.0
  package_config: ^2.1.0
  pana: 0.22.2
  path: ^1.8.0
  pub_updater: ">=0.3.1 <0.5.0"
  pubspec_parse: ^1.2.0
  stack_trace: ^1.10.0
  universal_io: ^2.0.4
  very_good_test_runner: ^0.2.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  build_version: ^2.1.1
  flutter:
    sdk: flutter
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0

executables:
  jolt:
