include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_print: true
    lines_longer_than_80_chars: false

analyzer:
  enable-experiment:
    - macros
