name: example_new
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.5.0"

dependencies:
  bitsdojo_window: ^0.1.6
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.2.8
  macros: ^0.1.2-main.4
  ui:
    path: ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: false
